### ISSUE TITLE
results arent always correctly calculated

### ISSUE THREAD

**Issue by JensTimmerman** [ZeusWPI/aichallenge#77] opened 2016-04-06 22:59 UTC
why is this a draw: https://zeus.ugent.be/battlebots/matches/65706 ?

**Comment by VandorpeDavid** [comment] 2016-04-07 00:17
https://zeus.ugent.be/battlebots/matches/65872
Another example. Might be useful for finding reproduction steps.

**Comment by VandorpeDavid** [comment] 2016-04-07 00:47
This seems to be specific to both Marmoer-bots (when they lose). Both have only draws and wins

**Comment by VandorpeDavid** [comment] 2016-04-07 01:04
My mistake: only Mamoerbot_v1.1 seems to be causing this.

**Comment by JensTimmerman** [comment] 2016-04-07 01:16
nope, also here https://zeus.ugent.be/battlebots/matches/66107

**Comment by VandorpeDavid** [comment] 2016-04-07 01:21
Ever since Java got fixed on the server, that jarbot also only has wins and draws.

**Closed** 2016-04-07 08:37 UTC
